### ISSUE TITLE
Poggit CI is not enabled

### ISSUE THREAD

**Issue by inxomnyaa** [ParoxityTeam/Commando#18]
this fork doesn't seem to be built at poggit
The linked CI / poggit page leads to inaccessible
> Such project does not exist, or the repo does not have Poggit CI enabled.
https://poggit.pmmp.io/ci/ParoxityTeam/Commando/~

**Comment by inxomnyaa** [comment]
Actually, the readme link works [https://poggit.pmmp.io/ci/Paroxity/Commando](https://poggit.pmmp.io/ci/Paroxity/Commando/Commando)

**Comment by Aericio** [comment]
updated link
