### ISSUE TITLE
StringEnumArgument is unusable

### ISSUE THREAD

**Issue by radondev** [ParoxityTeam/Commando#3]
When using any argument inheriting from StringEnumArgument.php (BooleanArgument.php or custom) the server crashes with this error message: `TypeError: "spl_object_id() expects parameter 1 to be object, null given`.

Correct me if I'm wrong, but it seems like this [line ](https://github.com/Paroxity/Commando/blob/27e44dbf310d6fbb412ed59412eeb04110e77cc7/src/CortexPE/Commando/args/StringEnumArgument.php#L47) isn't correct.

(Using the latest build from poggit)

**Comment by unickorn** [comment]
This seems to be the issue https://github.com/DaPigGuy/Commando-4.0.0/commit/298c3337b46adbe43fd8c7d270746add45ea2e82
